#ifndef PR_MODBUS_PROTOCOL_H_
#define PR_MODBUS_PROTOCOL_H_

enum modbus_op {
    MODBUS_READ_COILS = 1,
    MODBUS_READ_DISCRETE_INPUTS = 2,
    MODBUS_READ_HOLDING_REGISTERS = 3,
    MODBUS_READ_INPUT_REGISTERS = 4,
    MODBUS_WRITE_SINGLE_COIL = 5,
    MODBUS_WRITE_SINGLE_REGISTER = 6,
    MODBUS_WRITE_MULTIPLE_COILS = 15,
    MODBUS_WRITE_MULTIPLE_REGISTERS = 16,
    MODBUS_READ_FILE_RECORD = 20,
    MODBUS_WRITE_FILE_RECORD = 21,
    MODBUS_READ_WRITE_REGISTERS = 23,
    MODBUS_READ_DEVICE_IDENTIFICATION = 43,
};

#endif
